[project]
name = "connect-layer2"
authors = ["Connect Layer2 Team"]
description = "Cross-layer blockchain interoperability network"
telemetry = false
requirements = []
[contracts.layer2-registry]
path = "contracts/layer2-registry.clar"
depends_on = []

[contracts.layer2-bridge]
path = "contracts/layer2-bridge.clar"
depends_on = []

[contracts.layer2-token]
path = "contracts/layer2-token.clar"
depends_on = []

[contracts.layer2-connector]
path = "contracts/layer2-connector.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
